services:
  langlearn3:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: langlearn3
      ports:
        - "8000:8000"
      env_file:
        - .env
      environment:
        - DATABASE_URL:"postgresql://postgres:secret@host.docker.internal:5432/lang-learn"
      restart: always
      extra_hosts:
        - "host.docker.internal:host-gateway"



